spring:
  datasource:
    url: jdbc:mysql://prod-db:3306/ruoyi?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: prod_user
    password: prod_pass

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
